### ISSUE TITLE
Site Down

### ISSUE THREAD

**Issue by jython234** [PocketBukkit/BeaconPE-Site#19]
Major bug here, main VPS is down. I repeat, VPS is down. Our websites are all down (Maven Repository still working, hosted on github :+1: ).

**Comment by optrusty** [comment]
I will check it out @jython234

**Comment by optrusty** [comment]
@jython234 yup everything is down

**Comment by jython234** [comment]
Web team I expect is working on it?

On Friday, January 23, 2015, optrusty <notifications@github.com> wrote:

> @jython234 <https://github.com/jython234> yup everything is down
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PocketBukkit/BeaconPE-Site/issues/19#issuecomment-71264294>
> .
>


--

**Comment by optrusty** [comment]
@jython234 Nope, @Comedyman937 Has to tackle it... Web Devs are completley shutdown. No SSH or Webmin

**Comment by jython234** [comment]
@optrusty I have a feeling our web site will be down for a LONG time.

**Comment by optrusty** [comment]
Back Ups Back Ups Back Ups they always work :)

**Comment by optrusty** [comment]
@jython234 I don't know about CM937, but you can point your domain to my ip
104.167.108.77 for now

**Comment by optrusty** [comment]
wrong ip
Here is the right ip 104.167.109.18

**Comment by Comedyman937** [comment]
There was an issue with our host and the VPS is suspended.  The invoice is paid but the service thinks otherwise.  I contacted Matt about it and the server should be back up soon.

**Comment by jython234** [comment]
Ok thanks for your help.

On Saturday, January 24, 2015, Philip Shilling <notifications@github.com>
wrote:

> There was an issue with our host and the VPS is suspended. The invoice is
> paid but the service thinks otherwise. I contacted Matt about it and the
> server should be back up soon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PocketBukkit/BeaconPE-Site/issues/19#issuecomment-71354415>
> .
>


--

**Comment by Comedyman937** [comment]
The server has been purged so everything is gone... 
I am honestly fed up with HostingItAlls service so we need to find a new, better host.  We have the funds in the PayPal account just let me know what service and I'll use the BeaconPE funds to get started.  I prefer a shared host from now on instead of a VPS.

**Comment by optrusty** [comment]
@comedyman937 http://cloudatcost.com and did we lose the forums or we can still reinstall it and I will be happy to host the website for you guys if you want...

**Comment by Comedyman937** [comment]
Since everything from the VPS is now gone it looks like we will have to reinstall it -.-'

**Comment by jython234** [comment]
@Comedyman937 how much money do we have available? (If you don't want it
public, send me a memo on irc) What is shared hosting? I was going to say
that Amazon web services is nice, not sure how much ram we need, but you
can get it free for one year with 1GB of RAM. You also get a year free of
s3, which is their storage service. Also, I forgot, you get a linux and
windows VPS free for a year (1GB of ram each).
On Monday, January 26, 2015, Philip Shilling <notifications@github.com>
wrote:

> Since everything from the VPS is now gone it looks like we will have to
> reinstall it -.-'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PocketBukkit/BeaconPE-Site/issues/19#issuecomment-71543923>
> .
>


--

**Comment by optrusty** [comment]
@jython234 shared hosting is a server that holds multiple websites on one server

**Comment by optrusty** [comment]
@comedyman937 @jython234 lets continue this on irc

**Comment by jython234** [comment]
I suggest Amazon, just saying. Shared hosting may not be a good idea with
the traffic we may get. Who knows what will happen to our project.

On Monday, January 26, 2015, optrusty <notifications@github.com> wrote:

> @comedyman937 <https://github.com/comedyman937> @jython234
> <https://github.com/jython234> lets continue this on irc
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PocketBukkit/BeaconPE-Site/issues/19#issuecomment-71553925>
> .
>


--

**Comment by jython234** [comment]
@optrusty that provider looks good, need to research more though.

On Monday, January 26, 2015, Alejandro Zeise <atzeise@gmail.com> wrote:

> I suggest Amazon, just saying. Shared hosting may not be a good idea with
> the traffic we may get. Who knows what will happen to our project.
>
> On Monday, January 26, 2015, optrusty <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> @comedyman937 <https://github.com/comedyman937> @jython234
>> <https://github.com/jython234> lets continue this on irc
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/PocketBukkit/BeaconPE-Site/issues/19#issuecomment-71553925>
>> .
>>
>
>
> --
>
>

--

**Comment by optrusty** [comment]
Somethings I know about the I am a customer and the other thing i know is they are backed by a company called fibernetics. I was fooled by one time thing too.

**Comment by jython234** [comment]
The one time thing is fake? xD.

On Monday, January 26, 2015, optrusty <notifications@github.com> wrote:

> Somethings I know about the I am a customer and the other thing i know is
> they are backed by a company called fibernetics. I was fooled by one time
> thing too.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PocketBukkit/BeaconPE-Site/issues/19#issuecomment-71575559>
> .
>


--

**Comment by optrusty** [comment]
@jython234 real...

**Comment by jython234** [comment]
How did you get fooled?

On Monday, January 26, 2015, optrusty <notifications@github.com> wrote:

> @jython234 <https://github.com/jython234> real...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PocketBukkit/BeaconPE-Site/issues/19#issuecomment-71585414>
> .
>


--

**Comment by optrusty** [comment]
Lets continue on irc please the you can ask all the questions you can ever imagine

**Comment by jython234** [comment]
I have to go to school... Be online at 4:30 CST.

On Tuesday, January 27, 2015, optrusty <notifications@github.com> wrote:

> Lets continue on irc please the you can ask all the questions you can ever
> imagine
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PocketBukkit/BeaconPE-Site/issues/19#issuecomment-71650395>
> .
>


--

**Comment by Comedyman937** [comment]
New hosting provider has been paid and the site can go back online there.  I am working on adding the Cron Job and a couple other things then I will release the DNS for the server. :)

**Comment by Comedyman937** [comment]
mins24.fastcpanelserver.com
mins24.fastcpanelserver.com
