### ISSUE TITLE
FreeDNS Acting up.

### ISSUE THREAD

**Issue by jython234** [PocketBukkit/BeaconPE-Site#21]
Well, I keep getting "unknown host" errors for jython234.blockserver.org, and sometimes repo.blockserver.org. Also, blockserver.org appears to have some weird "BeaconPE unavailable" page. Anyone know what's going on?

**Comment by Comedyman937** [comment]
Read your MemoServ on IRC

**Comment by jython234** [comment]
@Comedyman937 Got it, but how do I login?

**Comment by Comedyman937** [comment]
Just go to http://beaconpe.net/cpanel

**Comment by jython234** [comment]
Oh ok thanks.

On Wednesday, March 4, 2015, Philip Shilling <notifications@github.com>
wrote:

> Just go to http://beaconpe.net/cpanel
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PocketBukkit/BeaconPE-Site/issues/21#issuecomment-77141620>
> .
>


--

**Comment by optrusty** [comment]
Cool we got our own cpanel now..... @Comedyman937

**Comment by jython234** [comment]
Yeah, I'll take a look at it. As for our build server, I decided that we
should use TeamCity. Use google if you don't know what it is.

On Wednesday, March 4, 2015, optrusty <notifications@github.com> wrote:

> Cool we got our own cpanel now..... @Comedyman937
> <https://github.com/Comedyman937>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PocketBukkit/BeaconPE-Site/issues/21#issuecomment-77256684>
> .
>


--

**Comment by jython234** [comment]
@Comedyman937 Also, since we arn't using FreeDNS, all our subdomains are gone. I can't seem to add repo.blockserver.org to the github repository.

**Comment by jython234** [comment]
And @optrusty Your VPS won't work, my connection timed out.

**Comment by optrusty** [comment]
@jython234 I'll check it out and what do you mean to the "GitHub Repo"

**Comment by jython234** [comment]
@optrusty IRC.

**Comment by optrusty** [comment]
@Comedyman937 What DNS provider are we using now?

**Comment by optrusty** [comment]
@jython234 IRC?
